### ISSUE TITLE
TypeError: Object [object Function] has no method 'CGMainDisplayID'

### ISSUE THREAD

**Issue by trabulmonkee** [hugs/node-castro#1]
I am getting this error when executing this command
$ node

> castro = require('castro')
> { Castro: [Function] }
> movie = new castro.Castro()
> TypeError: Object [object Function] has no method 'CGMainDisplayID'
>     at Object.Castro (/path to dir/node_modules/castro/castro.js:21:24)
>     at repl:1:10
>     at REPLServer.self.eval (repl.js:110:21)
>     at Interface.<anonymous> (repl.js:239:12)
>     at Interface.EventEmitter.emit (events.js:95:17)
>     at Interface._onLine (readline.js:202:10)
>     at Interface._line (readline.js:531:8)
>     at Interface._ttyWrite (readline.js:760:14)
>     at ReadStream.onkeypress (readline.js:99:10)
>     at ReadStream.EventEmitter.emit (events.js:98:17)

Environment
$ node -v
v0.10.25

$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.8.5
BuildVersion:   12F37

$ npm list castro
castro@0.0.2

Is there something else needed to be installed or upgraded, by chance, for AV Foundation Framework?  Or perhaps it is required to be at OS X 10.9.2?

**Comment by HLGgithub** [comment]
Same issue here- any word at all on this? Thank you

**Comment by hugs** [comment]
This issue is now quite old and probably not a problem anymore. For a while, Castro was requiring a version of NodObjC that became broken through later versions of Node and OS X. I think I've now fixed this by publishing a new version of Castro (0.3) that works with the latest version of nodobjc. (The case-sensitive "nodobjc" is now the new official npm package name for NodObjC.)

Castro 0.3 was tested with Node v4.5.0 on OS X El Capitan 10.11.6.

If you're still seeing this error, though, let me know.

**Comment by FlexShamil** [comment]
Hey there, the is legit tho as I am getting this when try to use castro package 
[09:25:22]  COMMAND     POST     "/wd/hub/session"
ERROR: $.CGMainDisplayID is not a function
chrome

└── castro@0.0.3

node -v
v8.9.4
