### ISSUE TITLE
windows: libc.dll not found

### ISSUE THREAD

**Issue by amaanmemon** [hugs/node-castro#2]
Error: Dynamic Linking Error: "libc.dll": The specified module could not be found.

**Comment by hugs** [comment]
This issue is now quite old and probably not a problem anymore. For a while, Castro was requiring a version of NodObjC that became broken through later versions of Node and OS X. I think I've now fixed this by publishing a new version of Castro (0.3) that works with the latest version of nodobjc. (The case-sensitive "nodobjc" is now the new official npm package name for NodObjC.)

Castro 0.3 was tested with Node v4.5.0 on OS X El Capitan 10.11.6.

If you're still seeing this error, though, let me know.
